# https://taskfile.dev
# TODO: Linter

version: '3'

tasks:
  generate:
    aliases: [migrate]
    desc: "Generate migrations for the database"
    dotenv: [".env"]
    cmds:
      - go run cmd/migrator/main.go --migrations-path "./migrations"
