env: "prod"

http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 60s

kafka:
  brokers: ["kafka:9092"]
  topic: "posts"
  group_id: "notification-service"

redis:
  address: "redis:6379"
  db: 0